### ISSUE TITLE
ID issues found by CI

### ISSUE THREAD

**Issue by sknorr** [SUSE/technical-reference-documentation#1]
@bwgartner For SEO reasons, we have moved (most of) the SUSE docs to using IDs that only contain the characters `a-z0-9-`. The CI is checking that by default & that's why it is failing currently. There are two options here:

1. Disable the check (we currently do that on the SBP repo)
2. Update the IDs

Longer-term, I'd definitely prefer (1), but shorter-term, we can do (2) if this is easier for you right now--[that option adds just a single line to our GitHub Actions workflow](https://github.com/openSUSE/doc-ci/tree/gha-validate#readme).
What do you think?

**Comment by sknorr** [comment]
It's actually not about file names but about these IDs:

```
Fatal error: The following IDs contain unwanted characters:
  G_Automation
  G_Availability
  G_Best-Practice
  G_Integrity
  G_PoC
  G_Production
  G_RA
  G_RC
  G_Scaling
  G_Security
```

**Comment by bwgartner** [comment]
> Thanks--though the issue is actually not about file names but about these IDs with underscores:
> 
> ```
> Fatal error: The following IDs contain unwanted characters:
>   G_Automation
>   G_Availability
>   G_Best-Practice
>   G_Integrity
>   G_PoC
>   G_Production
>   G_RA
>   G_RC
>   G_Scaling
>   G_Security
> ```

adjusted the above (and other IDs as well), see latest check-in (and seems the workflow checks now pass)
> 
> (Albeit, I don't like uppercase in file names all that much either -- so I do like the file name changes too :) .)

Since many were product names/proper nouns, tis why I had gone down that path, but okay with this change as well.
