### ISSUE TITLE
[doc] Issue in "Rancher by SUSE and Priority Support on AWS Marketplace" - please remove

### ISSUE THREAD

**Issue by kevinayres** [SUSE/technical-reference-documentation#104]
Rancher by SUSE and Priority Support on AWS Marketplace:

https://documentation.suse.com/trd/kubernetes/single-html/gs_rancher_aws-marketplace/?_gl=1*oz4ro9*_ga*MTc4NDkyMDgzMy4xNzA1NjA2NDM5*_ga_Y7SFXF9L00*MTcwNjMwMzY4MC40LjEuMTcwNjMwOTE5Ny41Ny4wLjA.#id-1

Can we please remove this TRD? There is a new Marketplace Listing for Rancher and this no longer applies. The new instructions are contained within the listing.

**Comment by tlssuse** [comment]
@chabowski : Are you able to help move this documentation into the TRD archive?  It is causing some confusion, as it references a marketplace listing that no longer exists.  ~ Terry

**Comment by chabowski** [comment]
@kevinayres @tlssuse the document is de-published. We will soon set up an archive for deprecated TRDs. Thanks for letting me know.
