### ISSUE TITLE
[doc] Issue in "MongoDB Enterprise with SUSE Rancher" - out-of-date

### ISSUE THREAD

**Issue by tlssuse** [SUSE/technical-reference-documentation#105]
MongoDB Enterprise with SUSE Rancher:

https://documentation.suse.com/trd/kubernetes/single-html/kubernetes_gs_rancher_mongodb-enterprise/#id-1

This documentation is out-of-date, featuring unsupported components.

@chabowski : Can you facilitate archiving this documentation?

**Comment by chabowski** [comment]
Hi @tlssuse the document is de-published. We will soon set up an archive for deprecated TRDs. Thanks for letting me know.
