### ISSUE TITLE
[doc]  Prerequisites

### ISSUE THREAD

**Issue by MG-MW** [SUSE/technical-reference-documentation#38]
Prerequisites:

https://documentation.suse.com/trd/linux/html/gs_sles_jupyter-jupyterlab/index.html#id-prerequisites

> Python 3.6 is included with SLES 15 SP4 and is used in this guide. This is adequate to run JupyterLab and many ML toolkits.

[endoflife.date/python](https://endoflife.date/python): Python `3.6` support ended 11 months ago. Accordingly, many ML toolkits don't support it anymore. 

One popular example, [scikit-learn](https://pypi.org/project/scikit-learn/), doesn't even support `3.7`. Currently, `3.9` seems to best supported python version with the longest remaining support. It's also the default version for the current anaconda [distribution](https://www.anaconda.com/products/distribution#Downloads).

**Comment by tlssuse** [comment]
Thank you for your comment.  This needs to be updated, as Python 3.10 is currently available in the SLES 15 SP4 repositories, and it is not that difficult to install whichever version or implementation (including the Anaconda distribution) of Python one might need.
We'll put this document into the queue for an update.
Again, thank you for providing feedback.  It is most appreciated.

**Comment by tlssuse** [comment]
PR for document updates has been submitted.
