### ISSUE TITLE
[doc] Issue in "Rancher by SUSE and Priority Support on AWS Marketplace"

### ISSUE THREAD

**Issue by kevinayres** [SUSE/technical-reference-documentation#55]
Rancher by SUSE and Priority Support on AWS Marketplace:

https://documentation.suse.com/trd/kubernetes/html/gs_rancher_aws-marketplace/index.html#

Terry is an author. I'm sorry, I thought I fixed this. Please change:

Contributor
Terry Smith, Global Partner Solutions Director (SUSE)

to read - 

Authors
Kevin Ayres, Solutions Architect (SUSE)
Terry Smith, Global Partner Solutions Director (SUSE)

Contributor
Stephen Mogg, Solutions Architect (SUSE)
Contributor
Keith Pettit, Sales Engineer (SUSE)

**Comment by tlssuse** [comment]
Merged with issue #56
