### ISSUE TITLE
[doc] Issue in "Priority support"

### ISSUE THREAD

**Issue by kevinayres** [SUSE/technical-reference-documentation#56]
Priority support:

https://documentation.suse.com/trd/kubernetes/html/gs_rancher_aws-marketplace/index.html#id-priority-support

The corrected URL for the SCC is https://scc.suse.com/cloudsupport

**Comment by tlssuse** [comment]
Making updates on gs-rancher-aws-issue-56 branch

**Comment by tlssuse** [comment]
Merged issue #55 into this issue.
