### ISSUE TITLE
[doc] Issue in "Setting up WordPress"

### ISSUE THREAD

**Issue by sjohal21** [SUSE/technical-reference-documentation#87]
Setting up WordPress:

https://documentation.suse.com/trd/linux/html/linux_gs_wordpress-lamp-sles/index.html#id-setting-up-wordpress

The command in step 4 says to copy to /src/www/htdocs/wp-config.php rather than the srv directory, which causes the command to fail.

**Comment by chabowski** [comment]
Hi @jamesongithub would you mind having a look at this issue, please? Thank you!

**Comment by chabowski** [comment]
This is fixed and should be publicly available after the next repo build. Thank you!
