### ISSUE TITLE
[doc] Issue in "Building a container image"

### ISSUE THREAD

**Issue by sreeves** [SUSE/technical-reference-documentation#94]
Building a container image:

https://documentation.suse.com/trd/linux/single-html/gs_sles_ibm-hpvs/#id-building-a-container-image

In order to build with the BCI image you need to add a line to checkout the 'slebci-paynow-website' branch, otherwise it will pull from upstream node19

git clone https://github.com/mfriesenegger/paynow-website.git
cd paynow-website
git checkout slebci-paynow-website  /*add this line */

**Comment by mfriesenegger** [comment]
@sreeves Thank you for pointing out this mistake in my TRD.  I will work with @tlssuse to get a fix to the documentation published ASAP.

**Comment by mfriesenegger** [comment]
@sreeves The change is merged.  I think this issue can be closed if you agree.
